name: Terraform GCP VM Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write GCP Credentials
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > credentials.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="gcp_credentials=$(cat credentials.json)"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="gcp_credentials=$(cat credentials.json)"
